# Fichier principal .gitlab-ci.yml (pipeline parent)
variables:
  GLOBAL_VAR: "Je suis héritée"
  SECRET_VAR: "Je ne devrais pas être héritée"

stages:
  - deploy

# Suppose l'existence d'un pipeline enfant
trigger-child:
  stage: deploy
  trigger:
    include: "child-pipeline.yml"
  inherit:
    variables: false  # Désactive l'héritage des variables